language: scala
jdk: oraclejdk8
sudo: false
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
before_deploy:
  - openssl aes-256-cbc -K $encrypted_4715f1439d03_key -iv $encrypted_4715f1439d03_iv
    -in service-account.json.enc -out service-account.json -d
  - sbt dist
deploy:
  provider: gae
  keyfile: service-account.json
  project: pts6-bijbaan
  skip_cleanup: true

